spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris:
      - http://172.22.105.146:9200
      - http://172.22.105.147:9200
      - http://172.22.105.38:9200
      - http://172.22.105.39:9200
    socket-timeout: 30s
    connection-timeout: 10s
#    username: xxx
#    password: